import javax.swing.*;
import java.awt.*;
import java.io.File;

public class buttonDemo extends javax.swing.JFrame {

    public buttonDemo() {
        initComponents();
        setupButtonGroup();
        setupActionListeners();
    }

    private void setupButtonGroup() {
        ButtonGroup petGroup = new ButtonGroup();
        petGroup.add(jRadioButton1);
        petGroup.add(jRadioButton2);
        petGroup.add(jRadioButton3);
        petGroup.add(jRadioButton4);
        petGroup.add(jRadioButton5);
    }

    private void setupActionListeners() {
        jRadioButton1.addActionListener(e -> handlePetSelection("bird"));
        jRadioButton2.addActionListener(e -> handlePetSelection("cat"));
        jRadioButton3.addActionListener(e -> handlePetSelection("dog"));
        jRadioButton4.addActionListener(e -> handlePetSelection("rabbit"));
        jRadioButton5.addActionListener(e -> handlePetSelection("pig"));
    }

    private void handlePetSelection(String pet) {
        JOptionPane.showMessageDialog(
            this,
            "You selected: " + pet,
            "Pet Selection",
            JOptionPane.INFORMATION_MESSAGE
        );
        displayPetImage(pet);
    }

    // ✅ The fixed image display logic
    private void displayPetImage(String pet) {
        String[] extensions = {".jpg", ".jpeg", ".png", ".gif", ".bmp"};
        String imagePath = null;

        for (String ext : extensions) {
            File file = new File("image/" + pet.toLowerCase() + ext);
            if (file.exists()) {
                imagePath = file.getPath();
                break;
            }
        }

        if (imagePath != null) {
            try {
                ImageIcon icon = new ImageIcon(imagePath);
                Image scaledImage = icon.getImage().getScaledInstance(
                    jTextField1.getWidth(), jTextField1.getHeight(), Image.SCALE_SMOOTH
                );
                icon = new ImageIcon(scaledImage);

                // ✅ Use the text field as an image display area
                jTextField1.setText("");
                jTextField1.setHorizontalAlignment(JTextField.CENTER);
                jTextField1.setBackground(Color.WHITE);

                // Use a JLabel as an icon holder inside the text field area
                jTextField1.setLayout(new BorderLayout());
                jTextField1.removeAll(); // clear previous icon
                JLabel imageLabel = new JLabel(icon);
                imageLabel.setHorizontalAlignment(SwingConstants.CENTER);
                jTextField1.add(imageLabel, BorderLayout.CENTER);

                jTextField1.revalidate();
                jTextField1.repaint();

            } catch (Exception e) {
                jTextField1.setText("Error loading image: " + pet);
//                jTextField1.setIcon(null);
            }
        } else {
            jTextField1.removeAll();
            jTextField1.setText("Image not found for: " + pet);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRadioButton1.setText("bird");

        jRadioButton2.setText("cat");

        jRadioButton3.setText("dog");

        jRadioButton4.setText("rabbit");

        jRadioButton5.setText("pig");

        jTextField1.setName("jLabelImage "); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addGap(28, 28, 28)
                        .addComponent(jRadioButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buttonDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buttonDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buttonDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buttonDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buttonDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
